### ISSUE TITLE
How can i ignore the mention textLength?

### ISSUE THREAD

**Issue by Michael-indochat** [sodenn/lexical-beautiful-mentions#138]
I am working on computing the text length within an editor, but I would like to exclude the length of mentions. In other words, I want to calculate the length of the text content without including the characters related to mentions.

Here is the code snippet I am currently using to compute the text length:

```typescript
        <OnChangePlugin
          onChange={editorState => {
            editorState.read(() => {
              const root = $getRoot();
              const editorText = root.getTextContent();
              const editorTextLength = editorText.length;
              console.log(editorText.length)
            });
          }}
        />
```

How can I modify this to ignore the length of mentions within the text content? 
Any guidance or suggestions would be greatly appreciated !

**Comment by sodenn** [comment]
Hi @Michael-indochat, to get the length of the text content without including the characters related to mentions, you need to iterate through all nodes using the `getChildren` method and exclude `BeautifulMentionNode`. You can use the `$isBeautifulMentionNode` function to check if a node is a mention node.

**Comment by Michael-indochat** [comment]
That's it, thank you for your solution!

**Comment by Michael-indochat** [comment]
I'm still trying to figure out how to solve this requirement,
Shouldn't it be calculated in handleChange,
What about writing a Plugin to listen to the editor to calculate text?

Hope to be able to recommend me a detailed can reach,
  "Calculate the number of editor text, and ignore mentionNode" method

**Comment by sodenn** [comment]
Another way is to first use the `$nodesOfType` function to get all mention nodes and count the characters. You can then easily subtract the length from the total length:
```ts
editorState.read(() => {
  const mentionNodes = $nodesOfType(BeautifulMentionNode);
  const mentionNodesTextLength = mentionNodes.reduce((pre, curr) => {
    return pre + curr.getTextContent().length;
  }, 0);
  // ...
});
```

**Comment by Michael-indochat** [comment]
Could you please guide me on how to parse the `apiResponse`, so that I can replace `@{user_nickname}` with the corresponding `FriendName`?

```typescript
// Default initialValue
// Input
export const APIResponse = "Hey @{user_nickname}";
// Expected Output
<p>Hey <mention>FriendName</mention></p>

const mentionItems: Record<string, BeautifulMentionsItem[]> = {
  "@": [
    "FriendName",
  ],
};
```

### source code 

```typescript
import { InitialConfigType } from "@lexical/react/LexicalComposer";
import { $createParagraphNode, $getRoot } from "lexical";
import {
  $convertToMentionNodes,
  BeautifulMentionNode,
  ZeroWidthNode,
} from "lexical-beautiful-mentions";
import theme from "./editor-theme";

export const defaultInitialValue =
  "Hey @{user_nickname}";

function setEditorState(initialValue: string, triggers: string[]) {
  return () => {
    const root = $getRoot();
    if (root.getFirstChild() === null) {
      const paragraph = $createParagraphNode();
      paragraph.append(...$convertToMentionNodes(initialValue, triggers));
      root.append(paragraph);
    }
  };
}

const editorConfig = (
  triggers: string[],
  initialValue: string,
): InitialConfigType => ({
  namespace: "",
  theme,
  onError(error: any) {
    throw error;
  },
  editorState: setEditorState(initialValue, triggers),
  nodes: [BeautifulMentionNode, ZeroWidthNode],
});

export default editorConfig;

```

**Comment by Michael-indochat** [comment]
Thank you so much for your assistance! it will work.
