### ISSUE TITLE
Is there a solution to hide `@` or `#` mentionUI ?

### ISSUE THREAD

**Issue by Michael-indochat** [sodenn/lexical-beautiful-mentions#145]
I want to complete the mention through the selection or inject the mention through the button. The UI just wants to display the value, and I don't want to display @ or #.

Like this demo screen:
![Xnapper-2023-08-17-11 39 56](https://github.com/sodenn/lexical-beautiful-mentions/assets/114893149/b811fe06-f065-495d-a3ea-382fbfd443c0)

**Comment by sodenn** [comment]
Hi @Michael-indochat, you can use the theme to hide the trigger character:
```ts
const beautifulMentionsTheme: BeautifulMentionsTheme = {
  "@": {
    trigger: "hidden",
    value: `px-1 mx-px bg-green-600 ...`,
  },
}
```

**Comment by Michael-indochat** [comment]
Wow, what a cool solution, thanks for your reply
