### ISSUE TITLE
Custom Mention Node

### ISSUE THREAD

**Issue by darenmalfait** [sodenn/lexical-beautiful-mentions#148]
Great work on this plugin, works like a charm.

> 2. Control rendering of the mention, beyond just styles. I want to add event handlers, so that I can display a tooltip on hover or a popover on click.

There is an option to override the behavior of Lexical Nodes. So you can override the default `BeautifulMentionNode` class and create your own `BeautifulMentionNodeWithTooltip` class. See https://lexical.dev/docs/concepts/node-replacement

_Originally posted by @sodenn in https://github.com/sodenn/lexical-beautiful-mentions/issues/101#issuecomment-1650355373_

            
I've been looking into this and I'm not sure how to do it. A param for custom node would be great, or otherwise some documentation on how to do it would properly also would help me.

**Comment by sodenn** [comment]
Hi @darenmalfait, I'll add some documentation about custom mention nodes, but I had to take a deeper look in [Node Overrides](https://lexical.dev/docs/concepts/node-replacement) first.
