### ISSUE TITLE
when removing hashtag or mention Close keyboard in android

### ISSUE THREAD

**Issue by hesamhadadi** [sodenn/lexical-beautiful-mentions#200]
**Describe the bug**

**To Reproduce**
1. Go to 'type hashtag or mention'
2. Write @ or # trigger to show Recommend List items
3. delete that 

**Expected behavior**
when removing hashtag or mention Close keyboard in android

**Screenshots**

**Desktop (please complete the following information):**
 - OS: android

**Smartphone (please complete the following information):**
 - Device: xiaomi note 11
 - OS: android 12
 - Browser google chrome

**Additional context**

**Comment by sodenn** [comment]
Hi @hesamhadadi. I am not sure if I understand the issue correctly. I tested the following steps on Android 12 and 13.
1. Open the example app: https://lexical-beautiful-mentions-docs.vercel.app/?value=
2. Enter `@` or `#` to open the mention list
3. Press backspace to remove the `@` or `#`

Result: The keyboard stays open.

**Please be aware**: The plugin currently does not work well on Android. There is a problem with the Android keyboard and lexical that affects this plugin: https://github.com/facebook/lexical/issues/4636

**Comment by quanvan1999** [comment]
@sodenn  I cannot remove the mention on my mobile Android phone and close the keyboard for your example. 

https://github.com/sodenn/lexical-beautiful-mentions/assets/55340595/c0c943c5-5cf1-43a2-a535-b63562dcb969
