### ISSUE TITLE
Allow "/" as a mention trigger

### ISSUE THREAD

**Issue by xTRam1** [sodenn/lexical-beautiful-mentions#206]
**Is your feature request related to a problem? Please describe.**
I want to build a text editor which support Slack-like forward slash "/" commands but [this check](https://github.com/sodenn/lexical-beautiful-mentions/blob/c67994ec1a7f6596ef138e55cef9483c251463ab/plugin/src/BeautifulMentionsPlugin.tsx#L263C4-L263C4) prevents me from using "/" as a trigger.

**Describe the solution you'd like**
Is it possible if this check is optional? Would it be as simple as adding an additional boolean prop field "checkSlash" to `BeautifulMentionsPluginProps`?

**Describe alternatives you've considered**
I have considered "//" or "/:" but they are pretty unusual replacements. I am already using @ and # for different kinds of mentions. 

**Additional context**
I just want to say that this package is amazing! Truly a life-saver for a front-end beginner like me :)

**Comment by sodenn** [comment]
Thank you @xTRam1. Originally the check for the slash comes from the lexical Playground, which I used as a template for this plugin. Now, I see no reason to keep it. I can remove the check it in the next release.

**Comment by xTRam1** [comment]
Thank you @sodenn! Can't wait for the next release :)
