### ISSUE TITLE
onSelectOption prop

### ISSUE THREAD

**Issue by xTRam1** [sodenn/lexical-beautiful-mentions#228]
**Is your feature request related to a problem? Please describe.**
Is it possible to provide our custom own `handleSelectOption` function to the plugin which can replace [this](https://github.com/sodenn/lexical-beautiful-mentions/blob/0b0c6bc3fd52c4d426e41268fb96f140c411a4bf/plugin/src/BeautifulMentionsPlugin.tsx#L228) function? I want to be able to customize how some mention types are displayed.

**Describe the solution you'd like**
It can be a prop similar to `onMenuClose`/`onMenuOpen` like `onSelectOption` with the following signatures:
```
(
  selectedOption: MenuOption,
  nodeToReplace: TextNode | null,
  closeMenu?: () => void,
) => void
```
just as it is currently.

**Describe alternatives you've considered**
I considered defining a custom mention component but my specific problem cannot be solved by that.

**Comment by sodenn** [comment]
Hi @xTRam1 
should `onSelectOption` really be a complete replacement for the default logic or should it be called in addition to the default logic? 
For the `combobox`, I already provided a `onComboboxItemSelect` prop which is called in addition to the default logic. I can adopt this for the menu as well and provide a `onMenuItemSelect` prop. Would that be enough?

**Comment by xTRam1** [comment]
Yes, that would be perfect. Thank you :)
