### ISSUE TITLE
Allow null or object for BeautifulMentionsItem

### ISSUE THREAD

**Issue by franzwarning** [sodenn/lexical-beautiful-mentions#229]
Hey! Love the repo. Wondering what your thoughts are on allowing `null` or `object` for `type BeautifulMentionsItem`? Here's a use case (and feel free to lmk the correct way if this doesn't make sense):

I want to show tiny profile avatars in the @ trigger node. Some users have avatars, some don't. Would be great to pass null for that data instead of the empty string (what I'm currently doing).

Does this make any sense? Lmk! Thanks!

**Comment by franzwarning** [comment]
But the data you need to return in the  `onSearch` function (a `BeautifulMentionsItem[]`) doesn't allow null as a value -- so you get a typescript error no?

**Comment by sodenn** [comment]
You mean the return value of the `onSearch` function should be optional? Can you give me an example of what you mean by "empty string"? Or do you mean an empty array?

**Comment by franzwarning** [comment]
On search expects this return type:
```
(property) onSearch: (trigger: string, queryString?: string | null | undefined) => Promise<BeautifulMentionsItem[]>
```

`BeautifulMentionsItem[]` looks like this:
```
export type BeautifulMentionsItem = string | {
    /**
     * The mention without the trigger character(s).
     */
    value: string;
    [key: string]: string | boolean | number;
};
```

So if I want to return an item with a null property -- like avatar, for example, I get a typescript error b/c of the `[key: string]: string | boolean | number` above.

My recommendation would be to change that to `[key: string]: string | boolean | number | null`.

Does that make sense?

**Comment by franzwarning** [comment]
thank you!!
