### ISSUE TITLE
Type custom-beautifulMention in node CustomBeautifulMentionNode does not match registered node

### ISSUE THREAD

**Issue by tecoad** [sodenn/lexical-beautiful-mentions#237]
**Describe the bug**
I am getting the following error when adding a mention with the createBeautifulMentionNode

```
Create node: Type custom-beautifulMention in node CustomBeautifulMentionNode does not match registered node CustomBeautifulMentionNode with the same type
```

**To Reproduce**
1. Create the custom node:

```
export const CustomMentionComponent = forwardRef<
	HTMLDivElement,
	BeautifulMentionComponentProps
>(({ trigger, value, children, ...other }, ref) => {
	return (
		<div {...other} ref={ref} title={trigger + value}>
	        prefix {value} suffix
		</div>
	);
});
```

2. Add a node in the config
```
		nodes: [...createBeautifulMentionNode(CustomMentionComponent)],
```

**Expected behavior**
On the editor try to add a mention

**Screenshots**
<img width="1190" alt="Screenshot 2023-11-12 at 20 44 25" src="https://github.com/sodenn/lexical-beautiful-mentions/assets/2627749/5e929d95-c1ad-4499-a6e6-d4fe44ac198b">

**Desktop (please complete the following information):**
- Chrome Version 119.0.6045.123 (Official Build) (arm64) on MacOS 13.5

**Comment by sodenn** [comment]
Hi @tecoad, thanks for reporting this. I was able to reproduce the error but only when running my example app in dev mode and after a hot reload (after changing code). When I build the app and run it in production mode, the error does not occur. Have you noticed the same behavior?

**Comment by tecoad** [comment]
Hi @sodenn , in my case, it happens in dev (local), but regardless of a hot reload. Which means the error is consistant.
Also tried to run your deployed repository with yarn and had the same issue...
Did you investigate?

**Comment by sodenn** [comment]
When calling `createBeautifulMentionNode`, a new class reference is created each time. I think this is causing the error. I think we need to cache the class reference and reuse it.

**Comment by tecoad** [comment]
Thanks!
That works for me!

**Comment by tecoad** [comment]
@sodenn If you allow me, can you clarify how can achieve the following result?

- i am using this extension to enable user insert variables in the following format: {variable}. So thats why i have to use a CustomMentionComponent to be able to render the brackets '{}' before/after.
However whenever I save or copy the value in the clipboard, the value that is being saved is still __trigger+__value, which would result {mentionItem .... how can a fix this behaviour?
