### ISSUE TITLE
Case of use: variables

### ISSUE THREAD

**Issue by tecoad** [sodenn/lexical-beautiful-mentions#250]
i am using this extension to enable user insert variables in the following format: {variable}. So thats why i have to use a CustomMentionComponent to be able to render the brackets '{}' before/after.
However whenever I save or copy the value in the clipboard, the value that is being saved is still __trigger+__value, which would result {mentionItem .... can this be replaced?

**Comment by sodenn** [comment]
Hi @tecoad, I think you need to implement your own `CustomMentionsNode` and override the `getTextContent` method: https://lexical.dev/docs/api/classes/lexical.LexicalNode#gettextcontent. Follow the first example in the README to create your own `CustomMentionsNode` class.

**Comment by sodenn** [comment]
After some digging, I found out that it makes a difference if I select the whole text in the editor including the mentions and copy it to the clipboard or if I select a single mention and try to copy it to the clipboard. Selecting and copying a single mention does not work at the moment. I will try to fix this in the next release.

**Comment by tecoad** [comment]
I have just impleented the CustommentionNode, i was using the helper class previously. 
In my case both selected whole text and one mention node is working.
Thanks for this great plugin.
Closing this issue for now.
