### ISSUE TITLE
Registering another KEY_ENTER_COMMAND blocks the menu from closing

### ISSUE THREAD

**Issue by demsr** [sodenn/lexical-beautiful-mentions#272]
**Is your feature request related to a problem? Please describe.**
I use lexical and your plugin to build a chat like application. To send messages I registered a KEY_ENTER_COMMAND with low priority which blocks further command execution. But now when I add a mention and I try to select a mention item with enter my command gets executed first and prevents the mention plugin from closing the menu and adding the selected mention

**Describe the solution you'd like**
Raise the command priority to medium 

**Describe alternatives you've considered**
Expose the command priority as a prop

**Comment by sodenn** [comment]
Hi @demsr. Is it possible to return `false` in your listener? That tells the editor that the command is not completed and other listeners will continue receiving the event, including the mention plugin.

**Comment by demsr** [comment]
@sodenn but my command isn't supposed to run at this point. When the mention menu is open it should insert the mention and not run my command at all...
