### ISSUE TITLE
When creating a mention the cursor goes back in the line. 

### ISSUE THREAD

**Issue by albertsalgueda** [sodenn/lexical-beautiful-mentions#307]
When I create a new mention, the cursor goes back the beginning of the line. Any idea on why this might be happening?

MY implementation is quite simple:

`import React, { useRef, useEffect, useCallback } from 'react';
import { $getRoot,
  $getSelection, 
  createEditorState, 
  $serializeEditorStateToMarkdown, 
} from 'lexical';
import {LexicalComposer} from '@lexical/react/LexicalComposer';
import {ContentEditable} from '@lexical/react/LexicalContentEditable';
import {HistoryPlugin} from '@lexical/react/LexicalHistoryPlugin';
import {RichTextPlugin} from '@lexical/react/LexicalRichTextPlugin';
import { ListPlugin} from '@lexical/react/LexicalListPlugin'
import { LinkPlugin } from "@lexical/react/LexicalLinkPlugin";
import { ClearEditorPlugin} from '@lexical/react/LexicalClearEditorPlugin';
import LexicalErrorBoundary from '@lexical/react/LexicalErrorBoundary';
import {OnChangePlugin} from '@lexical/react/LexicalOnChangePlugin';
import { AutoFocusPlugin } from "@lexical/react/LexicalAutoFocusPlugin";
import editorTheme from '../../theme/editorTheme';
import {
  BeautifulMentionsPlugin,
  BeautifulMentionNode
} from "lexical-beautiful-mentions";
import { MenuItem, MenuList } from '@mui/material';

const CustomMenuList = React.forwardRef(({ children, ...other }, ref) => {
  return (
    <MenuList  ref={ref} {...other} 
    style={{ position: 'absolute', bottom: '100%', background:'black', borderRadius: '10px' }}>
      {children}
    </MenuList>
  );
});

// Custom MenuItem component
const CustomMenuItem = React.forwardRef(({ children, ...other }, ref) => {
  return (
    <MenuItem fullWidth ref={ref} {...other} >
      {children}
    </MenuItem>
  );
});

const beautifulMentionsTheme = {
  "@": "mention",
  "#": "hashtag",
  "due:": "time"
};

const editorThemeWithMentions = {
  ...editorTheme, 
  beautifulMentions: beautifulMentionsTheme, 
};

const initialConfig = {
  namespace: 'MyEditor',
  theme: editorThemeWithMentions,
  nodes: [BeautifulMentionNode],
  onError: (error) => {
    console.error(error);
  },
};

const mentionItems = {
    "@": ["Anton", "Boris", "Catherine", "Dmitri", "Elena", "Felix", "Gina"],
    "#": ["Apple", "Banana", "Cherry", "Date", "Elderberry", "Fig", "Grape"],
    "due:": ["Today", "Tomorrow", "This week", "Next week", "This month", "Next month", "This Quarter", "Next quarter", "This year", "Next year"],
  };

const Editor = ({handleContentChange }) => {
  
  function onChange(editorState) {
    editorState.read(() => {
      const root = $getRoot();
      const textContent = root.getTextContent();
      handleContentChange(textContent);
    });
  };

  return (
    <>
      <LexicalComposer initialConfig={initialConfig}>
        <RichTextPlugin
          contentEditable={<ContentEditable style={{outline:'none', border:'none'}}/>}
          placeholder={<div className='editor-placeholder'>What's in your mind?</div>}
          ErrorBoundary={LexicalErrorBoundary}
        />
        {/* <ClearEditorPlugin/> */}
        <HistoryPlugin />
        <AutoFocusPlugin />
        <OnChangePlugin onChange={onChange}/>
        <BeautifulMentionsPlugin
          items={mentionItems}
          menuComponent={CustomMenuList}
          menuItemComponent={CustomMenuItem}
        />
      </LexicalComposer>
    </>
  );
};

export default Editor;`

**Comment by vekaev** [comment]
try to add `<AutoFocusPlugin defaultSelection="rootEnd" />`
