### ISSUE TITLE
`OPEN_MENTION_MENU_COMMAND` Doesn't to Open Menu Without Preceding Space When Selection Begins with a Symbol

### ISSUE THREAD

**Issue by vekaev** [sodenn/lexical-beautiful-mentions#323]
**Describe the bug**
In the `lexical-beautiful-mentions` plugin, the `OPEN_MENTION_MENU_COMMAND` does not add a space before the selection. This causes an issue where the mention menu does not open as expected.

**To Reproduce**
1. Go to a page with a textarea using `lexical-beautiful-mentions`.
2. Try to open the mention menu without adding a space before the selection.
3. Notice that the mention menu does not open.

**Expected behavior**
The `OPEN_MENTION_MENU_COMMAND` should add a space before the selection, allowing the mention menu to open correctly.

**Comment by sodenn** [comment]
I can't reproduce this issue on the demo page: https://lexical-beautiful-mentions-docs.vercel.app/. Could you provide an example video?

**Comment by vekaev** [comment]
You can simply double-click to open the suggested options

**Comment by sodenn** [comment]
So it only affects trigger characters, right? In other words, the menu should open if there is another trigger character directly in front of the cursor. What exactly is the use case for this? Because the menu opens after the first click on "Open Suggestion", doesn't it?

**Comment by NatalyGraham** [comment]
It is not possible to mention someone without adding space character before a trigger. Use case described in a picture.
![2024-03-12 132055](https://github.com/sodenn/lexical-beautiful-mentions/assets/62985553/fe6c9c51-541b-434e-99ff-26e59ff3238b)

**Comment by theigor** [comment]
@sodenn - @NatalyGraham above has a great usecase that affects us as well. we're using beautiful mentions to insert variables in text and we can't pull up any suggestions when the trigger character is next to another character. so for example, in github you can say (@sodenn) - notice that the @ is next to the ( but in beautiful mentions, we'd have to do ( @sodenn - notice the space between.

**Comment by sodenn** [comment]
There is already an exception in the mention regex to allow the user to type an open bracket `(` before the trigger character.
Of course, we can add additional characters to this Regex, but I think we need to be careful. Sometimes the user doesn't want that the menu pops up - for example, when typing an email address. What about adding a configuration option to allow developers to define their own exceptions?

**Comment by rycornell** [comment]
I'm also interested in this feature.  Our trigger is `${` and the selected item can be inserted after any character.  It is used in URLs and JSON objects.

**Comment by theigor** [comment]
> There is already an exception in the mention regex 

Maybe provide this as a prop so it does the default exception but you can customize to your use case?
