### ISSUE TITLE
`$` cannot be used as trigger character

### ISSUE THREAD

**Issue by chaconam** [sodenn/lexical-beautiful-mentions#338]
**Describe the bug**
It doesn't work when `$` is used as a trigger character. It seems it's caused by `$` being a special character (end of line) in regex.
I am trying to use it as a stock symbol. `$` is widely used as a stock symbol on Twitter.

**To Reproduce**
1. use '$' as a trigger character

**Expected behavior**
It should work normally accepting `$` as a trigger character.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac,windows
 - Browser: chrome, safari
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: latest

**Additional context**

https://github.com/sodenn/lexical-beautiful-mentions/blob/7145e445cda88aee9c979ac4656bad823e4faa0d/plugin/src/mention-utils.ts#L52

maybe surround trigger characters with `[` and `]` or escape with `\`?

**Comment by sodenn** [comment]
Hi @chaconam. You need to escape the `$` character:
```ts
const mentionItems = {
  "\\$": ["A", "B", "C"],
};
```
<img width="400" alt="Screenshot 2024-01-20 at 18 57 49" src="https://github.com/sodenn/lexical-beautiful-mentions/assets/232054/c8fbc9c1-bf92-4bb8-b426-5d8502b456f9">
