### ISSUE TITLE
Ability to add an empty state component when there are no results

### ISSUE THREAD

**Issue by yairco1990** [sodenn/lexical-beautiful-mentions#343]
Thank's for this great plugin!

**Describe the solution you'd like**
An ability to add an empty state component when there are no search results for a better user experience

**Comment by sodenn** [comment]
Hi @yairco1990, do you mean something like this:
<img width="316" alt="Screenshot 2024-01-23 at 19 49 44" src="https://github.com/sodenn/lexical-beautiful-mentions/assets/232054/f044430a-2299-4079-829b-8d004e7c1294">

**Comment by yairco1990** [comment]
exactly!
