### ISSUE TITLE
Append React 17 as a peer dependency

### ISSUE THREAD

**Issue by yamcodes** [sodenn/lexical-beautiful-mentions#347]
First of all I'd like to thank you for an awesome plugin.

We (unfortunately) still use React 17 for many projects at work and we would really like to use this plugin. 
Obviously, we can just force install it and ignore the warnings, but I'm not sure it's even necessary to demand React 18 in the first place.

Furthermore, when I did force-install, I've encountered 2 browser warnings with a project following the `README.md` example code.

![image](https://github.com/sodenn/lexical-beautiful-mentions/assets/2014360/e00224e3-71f9-4df9-9985-a3cfd3551513)

At that point I wasn't sure if these were attributed to us using React 17 or are just errors in the package.

To test this, I've played with a version of this repo (https://github.com/yamcodes/lexical-better-mentions) that is the same as this one, with a number of changes:
1. [Set React (and react-dom) 17 as the minimal peerDependency version](https://github.com/yamcodes/lexical-better-mentions/blob/f873838eea0876917d8fefa09e55964992b3ce65/plugin/package.json#L54)
2. Merging the [LexicalTypeaheadMenuPlugin PR](https://github.com/sodenn/lexical-beautiful-mentions/pull/345)
3. Removing the deprecated `itemValue` prop which was throwing the above warning
4. [Resorting to `loading={undefined}` when the prop is not set, and `true` otherwise ](https://github.com/yamcodes/lexical-better-mentions/commit/79748d8aba886cb51511f74049f38ded150aec22) so it's not passed to a DOM element (`ul` or `div` by default)

This solved all the warnings in my limited testing. I've also tested it this in a stripped down version of the Next.js `www` package (in React 18), and removing all props but `items` from the `<BeautifulMentionsPlugin>` threw the same `loading` DOM warning as above, implying the warning was not related to React 18 but an actual bug.

The reason this is flagged as a feature-request and not a direct PR is that some of [my tests were failing](https://github.com/yamcodes/lexical-better-mentions/actions/runs/7630474500).

I hope I was able to give some background to get this going, but I think if this project truly does not need React 18 features, it would be nice to open the gates for more users who could benefit from it. At the very least it would be more transparent of its actual requirements.

**Comment by sodenn** [comment]
Hi @yamcodes. It's probably a good idea to follow the supported React version of lexical. As long as lexical supports React 17 it should be fine.

You can get rid of the warning by deconstructing the props and passing the rest to the `ul` element:
```tsx
const MyMenu = forwardRef<any, BeautifulMentionsMenuProps>(
  ({ open, loading, ...other }, ref) => {
    return (
      <ul
        ref={ref}
        {...other}
      />
    );
  },
);
```

**Comment by fakob** [comment]
The above deconstructing helped me to get rid of the loading error, but I still get

```
Warning: React does not recognize the `itemValue` prop on a DOM element.
```

Am I missing something?
