### ISSUE TITLE
Cursor jumps to the beginning of the input on Safari

### ISSUE THREAD

**Issue by quocanhbk** [sodenn/lexical-beautiful-mentions#355]
**Describe the bug**
After selecting a mentioned users, the cursor visually jumps the the beginning of the input.

**To Reproduce**
1. Type some text and mention somebody by typing @ in the input.
2. Select a person from the list.
3. The cursor will automatically jump to the beginning of the input (visually).
4. If continue typing, the cursor will jump the end and work normally.

**Expected behavior**
The cursor should stay at the end after selecting a mentioned person.

**Screenshots**
The cursor visually jumps to the start after selecting a person:
<img width="629" alt="image" src="https://github.com/sodenn/lexical-beautiful-mentions/assets/64638082/0c6466a2-b29e-4026-95a0-b5b49653263d">
Ignore that and continue typing:
<img width="628" alt="image" src="https://github.com/sodenn/lexical-beautiful-mentions/assets/64638082/90c40d35-99ad-4df1-a4b8-fe7a094dc7b5">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 15.6

**Comment by sodenn** [comment]
Hi @quocanhbk. It is a known problem. I have created a ticket for this: https://github.com/facebook/lexical/issues/4487.
As a workaround, you can use the `ZeroWidthPlugin` which is included in lexical-beautiful-mentions:
```tsx
import {
  ZeroWidthNode,
  ZeroWidthPlugin,
  BeautifulMentionsPlugin,
} from "lexical-beautiful-mentions";

const editorConfig = {
  nodes: [ZeroWidthNode]
}

// ...

<ZeroWidthPlugin />
<BeautifulMentionsPlugin
  // ...
/>
```

**Comment by quocanhbk** [comment]
Thank you! That seem to fix the problem!

**Comment by rik-iso** [comment]
Evidently renamed to `PlaceholderPlugin` but works the same
