### ISSUE TITLE
Styled components default styling support

### ISSUE THREAD

**Issue by ido-journey** [sodenn/lexical-beautiful-mentions#365]
**Is your feature request related to a problem? Please describe.**
Styles are not working when project is not configured to use tw, mine has styled components

**Describe the solution you'd like**
Add styled components option to inherit default styles instead of making custom components

**Describe alternatives you've considered**
Currently im using the custom components to override which is an awesome feature but creates more boilerplate

**Additional context**
Awesome library!

**Comment by sodenn** [comment]
Hi @ido-journey. Do you mean an alternative to the CSS classes that are passed to the [lexical theme](https://lexical.dev/docs/getting-started/theming) prop?
```tsx
const editorConfig = {
  // ...
  theme: {
    beautifulMentions: {
      "@": "px-1 mx-px ...",
      "@Focused": "outline-none shadow-md ...",
    },
  },
};

<LexicalComposer initialConfig={initialConfig}>
  ...
</LexicalComposer>
```

**Comment by ido-journey** [comment]
Hi,
Actually i have a weird issue where i don't see mention, menu and menu item styles at all with default configuration,
Is it because i encapsulate the plugins with divs? 

` <LexicalComposer initialConfig={initialConfig}>
      <LoadInitialContent initialContent={defaultValue} />
      <div className={editable ? 'editor-container' : null}>
        {editable && <ToolbarPlugin />}
        <div className={editable ? 'editor-inner' : null}>
          <RichTextPlugin
            contentEditable={<ContentEditable className="editor-input" />}
            placeholder={<Placeholder placeholder={placeholder} />}
            ErrorBoundary={LexicalErrorBoundary}
          />
          {editable && (
            <>
              <HistoryPlugin />
              <AutoFocusPlugin />
              <ListPlugin />
              <LinkPlugin />
              <OnChangePlugin onChange={onEditorStateChange} />
              <MarkdownShortcutPlugin transformers={TRANSFORMERS} />
            </>
          )}
          <BeautifulMentionsPlugin
            creatable={false}
            emptyComponent={MentionsEmpty}
            items={mentionValues}
            onMenuItemSelect={menuItem => {
              onMention(menuItem['id']);
            }}
          />
        </div>
      </div>
    </LexicalComposer>`

and Also would been nice to pass overrides as styled components, or is it possible only with custom elements as prop?
thanks!

**Comment by sodenn** [comment]
It`s hard to know what is miss-configured without a full code example. Can you provide a code sandbox?

> and Also would been nice to pass overrides as styled components, or is it possible only with custom elements as prop?
thanks!

Have you tried the `createBeautifulMentionNode` helper function? It allows you to override the default mention node with a custom one. You can than use styled-components, emotion or any other library to style the custom mention node.

**Comment by canibanoglu** [comment]
Hi @sodenn, I thought I'd write in this issue first before creating one.
I'm having the exact same issue as @ido-journey. I have installed the plugin, added all the basic code from the `README` and I can't see anything related to this plugin. It "works", I can use arrow keys to blindly select a value and see the *text value* in the editor but none of the default styling is available. I'm also using styled components instead of tailwind. 

I'm not talking about custom styling or anything like that, just bare minimum installation doesn't display anything. Do you have any pointers?

**Comment by unodgs** [comment]
I can confirm this problem. I tried override `container` style but looks like it's not used. I can see in the DOM `#typehead-menu` is rendered.
