### ISSUE TITLE
The example code documents non-existing properties

### ISSUE THREAD

**Issue by yamcodes** [sodenn/lexical-beautiful-mentions#367]
**Describe the bug**

The example code under [Custom menu and menu item component](https://github.com/sodenn/lexical-beautiful-mentions#custom-menu-and-menu-item-component) uses the `open` and `ref` props that are not supplied in [the source code](https://github.com/sodenn/lexical-beautiful-mentions/blob/fb034197e027c5264a36b48ec167be57056aa9ba/plugin/src/BeautifulMentionsPlugin.tsx#L672).

**Additional questions**
1. Why does the example code and [the `www` `Menu`](https://github.com/sodenn/lexical-beautiful-mentions/blob/fb034197e027c5264a36b48ec167be57056aa9ba/www/components/Menu.tsx#L16) supply a `ref` if it's not used?
2. Why is the purpose of the `open` prop in the examples ([and `www`](https://github.com/sodenn/lexical-beautiful-mentions/blob/fb034197e027c5264a36b48ec167be57056aa9ba/www/components/Menu.tsx#L12)) and how is it managed?

**Comment by sodenn** [comment]
Hi @yamcodes. Thanks for the report. The example code is outdated. `open` and `ref` are not used. I will update it.
