### ISSUE TITLE
A few keyboard shortcuts don't work around mention nodes.

### ISSUE THREAD

**Issue by WesleyKapow** [sodenn/lexical-beautiful-mentions#382]
**Describe the bug**
Some keyboard shortcuts don't work with mentions.

**To Reproduce**
Cannot highlight preceding text when to the right of a mention node:
1. Go to https://lexical-beautiful-mentions-docs.vercel.app/
2. With the cursor immediately to the right of a mention at the end of the document (should be last node), try highlighting all preceding text with, CMD+SHIFT+UP_ARROW.
3. Notice the highlight flashes but doesn't stay. Interestingly this works if there's other text after the cursor.

Cannot jump to start or end of text line:
1. Go to https://lexical-beautiful-mentions-docs.vercel.app/
2. Put cursor within text between two mentions.
3. Hit control-A and control-E
4. Notice cursor jumps to start & end of current text node but not start/end of paragraph (text line) as it should

**Expected behavior**
Mention nodes have no impact on normal keyboard shortcuts for text editing.

**Additional context**
From https://support.apple.com/en-us/HT201236
> Control-A: Move to the beginning of the line or paragraph.
> Control-E: Move to the end of a line or paragraph.

**Comment by sodenn** [comment]
I pretty sure that the second issue is not related to the beautiful-mentions plugin, as I have tested it with other DecoratorNodes in the [lexical playground](https://playground.lexical.dev/) with the same result:
![2024-03-02 17 49 22](https://github.com/sodenn/lexical-beautiful-mentions/assets/232054/bd98d957-0ce1-42df-9dd1-336f2240727a)

**Comment by WesleyKapow** [comment]
I've opened https://github.com/facebook/lexical/issues/5680 to address the root cause. Thank you!
