### ISSUE TITLE
Possibility to pass an object instead of string for suggestion

### ISSUE THREAD

**Issue by matusca96** [sodenn/lexical-beautiful-mentions#44]
Hi, first of all thanks for this helpfull plugin library!

I would like to know if it's possible to pass an object in the items property, something like:

```const mentionItems: Record<string, { name: string; email: string }[]> = {
'@': [
    { name: 'Anton', email: 'anton@gmail.com' },
    { name: 'Boris', email: 'boris@gmail.com' },
    { name: 'Catherine', email: 'catherine@gmail.com' },
    { name: 'Dmitri', email: 'dmitri@gmail.com' },
    { name: 'Elena', email: 'elena@gmail.com' },
  ],
  '\\w+:': [],
};
```

I've tested and actually works, but not 100%, because I think the whole plugin is expecting just a string instead of an object. So in my menu item component I had to change it a little bit:

```
type SuggestionProps = Omit<BeautifulMentionsMenuItemProps, "children"> & { children: { name: string; email: string; } };

const Suggestion = forwardRef<HTMLLIElement, SuggestionProps>(({ children: { name, email }, ...rest }, ref) => {
  return (
    <li {...rest} aria-label={`Choose ${name}`} ref={ref}>
      <span>{name}</span>
      <span>{email}</span>
    </li>
  );
});
```

But this results in some unexpected behaviors, for example the onClick in the item, adds a `[Object object]` in the editor, if we try to filter a mention before selecting in the menu, for example "Hey @ant", after the `@` char, throws an error because is trying to filter based on a string.

So I'm not sure if this is possible, or if there is any other way to pass additional props to the menu item component instead of just a string.

Thanks a lot!

**Comment by sodenn** [comment]
Unfortunately, this is currently not possible and the implementation would be a bit challenging. What value `email` or `name` should be written to the editor when selecting an item from the menu? Is it possible to consider the string arrays in the `items` prop as unique keys that can be used to retrieve further information within your custom MenuItem component? For example:

```
const additionalData = {
  "Anton": "...",
  "Berta": "...",
  "Caesar": "...",
  // ...
}

const MenuItem = forwardRef<HTMLLIElement, BeautifulMentionsMenuItemProps>(
  ({ selected, children: label, ...props }, ref) => (
    <li
      ref={ref}
      className="flex ..."
      {...props}
    >
      {label} {additionalData[label]}
    </li>
  )
);
```

If that helps, I can add a `label` to `BeautifulMentionsMenuItemProps`. This is better than considering children as string. This is not safe and can change anytime.

**Comment by matusca96** [comment]
Hey @sodenn, thanks for the reply! Well, so I've ended to a different approach that for now solves my problem. The bad thing with what you said is that in my case I'm fetching the users remotely, so I don't have the users stored in any place to map in the `MenuItem` component. So what I did (and I think that should be other approaches), was create a context, and then everytime the `onSearch` is triggered and there are results, I'm setting this results in the context, and then I can use in the `MenuItem` component:

```
const Suggestion = forwardRef<HTMLLIElement, SuggestionProps>(({ children, ...rest }, ref) => {
  const { suggestions } = useMentions() // my custom hook to access the context
  
  const currentSuggestion = suggestions.find((item) => item.name === children)

  return (
    <li {...rest} aria-label={`Choose ${children}`} ref={ref}>
      <span>{currentSuggestion?.name ?? children}</span>
      <span>{currentSuggestion?.email ?? children}</span>
    </li>
  );
});
```

Maybe this is not the best solution, but at least for now it is working in my case. Thanks a lot for the help again!
