### ISSUE TITLE
Integrating mention plugin with TextNode

### ISSUE THREAD

**Issue by vs-amzn** [sodenn/lexical-beautiful-mentions#461]
**Is your feature request related to a problem? Please describe.**

So in its current state when we select a mention from the menu, a mention node is added to the editor. Then after inserting the mention in the editor, if we delete the entire mention is gone (which is expected, since its an entire node).

**Describe the solution you'd like**

I'd like to be able to selection a mention from the menu and update the editor with a text node that contains the value of the men item. This is so that after adding a mention, I can modify the mention inline (even if the mention doesn't exist).

For example if i searched for "#Anton", the editor would update but then i can hit the backspace and be in state "#Anto" (as opposed to #Anton being removed entirely)

**Describe alternatives you've considered**

At the moment, my only way around this is by creating a custom plugin. I tried creating a custom node that extends the BeautifulMentionNode but since BeautifulMentionNode is of type Decorator Node, it was a bit of a mess. 

**Additional context**

**Comment by vs-amzn** [comment]
Hi just following up here! Is there an opportunity to support this? Or are there any workarounds we can use?

**Comment by sodenn** [comment]
So that I understand correctly, you want to update already inserted mention nodes by placing the cursor inside the mention and typing (like a normal text node), correct?

**Comment by vs-amzn** [comment]
Sort of. When we pick a mention from the list, I'd like to insert a text node instead of a mention node. That way you can edit anything inline in the editor since they're all text nodes. The goal here is to be able to edit the mention after it's been inserted into editor without modifying or displaying the populated list of mentions that is rendered.
