### ISSUE TITLE
When the image causes the row to become higher, the popup of mention is not accurately located.

### ISSUE THREAD

**Issue by jaceyi** [sodenn/lexical-beautiful-mentions#467]
**Describe the bug**
When the image causes the row to become higher, the popup of mention is not accurately located.
![image](https://github.com/sodenn/lexical-beautiful-mentions/assets/26017405/e80e7f55-55d8-4b57-8da8-c6fc808df682)
![image](https://github.com/sodenn/lexical-beautiful-mentions/assets/26017405/2cdc8856-057d-423b-b328-a3cd43501fe9)
![image](https://github.com/sodenn/lexical-beautiful-mentions/assets/26017405/37fdf833-c3c4-48d5-b2ac-29fb55306359)
![image](https://github.com/sodenn/lexical-beautiful-mentions/assets/26017405/f6e2d8b2-7db1-48f1-a85a-d169b3f35f16)

**Comment by sodenn** [comment]
It looks like the `LexicalTypeaheadMenuPlugin` calculates a wrong position for the popup in this case:

<img width="500" alt="Screenshot 2024-04-29 at 19 54 17" src="https://github.com/sodenn/lexical-beautiful-mentions/assets/232054/9882cf02-1be6-406a-b209-cee86550f0b0">
