### ISSUE TITLE
LexicalComposerContext.useLexicalComposerContext: cannot find a LexicalComposerContext

### ISSUE THREAD

**Issue by wouterlemcke** [sodenn/lexical-beautiful-mentions#540]
Implementing the most basic form directly results in error.
```
<LexicalComposer
    initialConfig={{
        namespace: 'MyEditor',
        onError: console.error,
        nodes: [BeautifulMentionNode],
    }}
>
    <RichTextPlugin
        contentEditable={<ContentEditable />}
        placeholder={<div>Enter some text...</div>}
        ErrorBoundary={LexicalErrorBoundary}
    />
    <BeautifulMentionsPlugin items={mentionItems} />
</LexicalComposer>
```

![image](https://github.com/sodenn/lexical-beautiful-mentions/assets/2428956/73b9ab5d-a646-49b2-af39-84f650dd09c0)

I'm using lexical v16.1

**Comment by wouterlemcke** [comment]
Nevermind, found the issue. It was in my code

**Comment by Gregoor** [comment]
I'd be interested in hearing what the issue exactly was. The code you posted looks like mine (and correct, to my eyes). I'm also only seeing the issue with jsdom, it works in the real thing.

**Comment by FradiFrad** [comment]
@wouterlemcke Hi! I have the exact same error! What was the issue? Thank you!
