### ISSUE TITLE
Using useBeautifulMentions with CustomMentionComponent

### ISSUE THREAD

**Issue by richardwlb** [sodenn/lexical-beautiful-mentions#563]
**Describe the bug**
First of all, thank you for the plugin. 
Is it possible to use the functions from the `useBeautifulMentions` (like getMentions() for instance) when using a `CustomMentionComponent`? Even in the demo, when setting the `Custom mentions` the action of the button `Remove mention` does not work anymore.

**Comment by richardwlb** [comment]
Thank you!

**Comment by lukejacksonn** [comment]
Thank you for this, been wondering why `getMentions` was returning an empty array and this was the reason!
