### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getType')

### ISSUE THREAD

**Issue by GruFFix** [sodenn/lexical-beautiful-mentions#570]
Hello. I installed the plugin and then an error appeared.

TypeError: Cannot read properties of undefined (reading 'getType')

```
   <LexicalComposer initialConfig={INITIAL_CONFIG}>
        <RichTextPlugin
          contentEditable={<ContentEditable className={s.input} />}
          placeholder={<div className={s.placeholder}>123</div>}
          ErrorBoundary={LexicalErrorBoundary}
        />

        <BeautifulMentionsPlugin items={mentionItems} />
      </LexicalComposer>
```

A completely standard example, but when I try to specify a trigger in the text, an error appears

**Comment by sodenn** [comment]
I think I have found the error. It occurs when only the default `BeautifulMentionNode` is used (unlike in the demo). I will release a new version soon and fix it.
