### ISSUE TITLE
"onSearch?: undefined" in the BeautifulMentionsPlugin component,

### ISSUE THREAD

**Issue by eb-73** [sodenn/lexical-beautiful-mentions#582]
**Describe the bug**
I can't add onSearch prop to the component because of its type. =>Type '(trigger: string, query?: string | null) => Promise<BeautifulMentionsItem[]>' is not assignable to type 'undefined'.ts(2322) 

**To Reproduce**

**Expected behavior**

**Screenshots**
![code](https://github.com/user-attachments/assets/2b502f4b-c707-495a-b86a-3f796c696330)
<img width="514" alt="Screenshot 2024-07-28 102606" src="https://github.com/user-attachments/assets/f59caacf-cb8a-491a-be87-3027c883f5cd">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sodenn** [comment]
Hi @eb-73. You cannot use ‘items’ and ‘onSearch’ at the same time. You must remove one of these two props.
