### ISSUE TITLE
onSearch props

### ISSUE THREAD

**Issue by ebrhim94** [sodenn/lexical-beautiful-mentions#592]
**Describe the bug**
I need to write my onSearch method to search on custom data, not event name
my items format is like this => 
```
{
id: string;
name: string;
email: string;
value: string;
image: string;
}[]
```
,and I want to search on name and email to filter the suggestion list, but I think this code causes an extra rerender and it makes my app broken
<img width="337" alt="image" src="https://github.com/user-attachments/assets/dd797cff-d00d-4285-b9c4-3590facf259e">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sodenn** [comment]
Try to pass stable component references to the `menuComponent` and `emptyComponent` props by defining these components outside of your main component.
