### ISSUE TITLE
Cannot have a Display Value for the BeautifulMentionsPlugin with the MenuComponent

### ISSUE THREAD

**Issue by MedAzizKhayati** [sodenn/lexical-beautiful-mentions#621]
### Description
The prop `displayValue` is not taken into consideration when using the MenuComponent.

### To Reproduce
1. Add this demo items to the plugin.
```jsx
<BeautifulMentionsPlugin
    items={{ "{{": [ { value: "firstName}}", displayValue: "firstName" } ] }}
    ...
 />
```

### Expected behavior
The menu item list doesn't show the suffix for the items "}}".

### Screenshots of the problem
![image](https://github.com/user-attachments/assets/19363fb2-9ac7-4148-974a-40f7732927d0)

------------ EDIT ------------
### The part causing the bug
Click [here](https://github.com/sodenn/lexical-beautiful-mentions/blob/fbf63cc67424300e83cd4ee8325ce73ba2ed0d1f/plugin/src/BeautifulMentionsPlugin.tsx#L193-L201) for the exact code location.
```ts
// add options from the lookup service
let opt = results.map((result) => {
  if (typeof result === "string") {
    return new MentionOption(trigger, result, result);
  } else {
    const { value, ...data } = result;
    return new MentionOption(trigger, value, value, data);
  }
});
```
In here, the instance of `MentionOption` that is created uses the `value` for the `displayValue` which causes the bug.

**Comment by sodenn** [comment]
Hi @MedAzizKhayati ,

The `displayValue` prop currently cannot be overwritten directly. However, you can access all additional metadata via `props.item.data`. For Example:

```jsx
Code kopieren
const items = {
  "@": [
    { value: "Catherine", displayValue: "Catherine" },
  ],
};
```

You can then use `displayValue` prop from `item.data`:

```jsx
Code kopieren
const CustomMenuItem = forwardRef<
  HTMLLIElement,
  BeautifulMentionsMenuItemProps
>(({ item: { data: { displayValue }}, ...props }, ref) => (
 <li>{displayValue}</li>
));
```
