### ISSUE TITLE
Mention Trigger Behavior Inconsistency with Different Triggers

### ISSUE THREAD

**Issue by NatalyGraham** [sodenn/lexical-beautiful-mentions#661]
**Summary:**
When adding a mention trigger with a single character (like @ or #) before a word without spacing, a space is automatically added after the mention is selected, and the original word remains intact. However, when using a multi-character trigger (like due:), the original word is deleted after selecting the mention, which leads to inconsistent behavior.

**Steps to Reproduce:**

1.	Write or paste a word into the editor.
2.	Move the cursor to the beginning of the word.
3.	Start typing the mention trigger:

- **Case A:** Use a single-character trigger (@ or #).
   •	After typing the trigger, select a mention.
   •	**Observed Behavior:** A space is added, the mention is inserted, and the original word remains intact.

- **Case B:** Use a multi-character trigger (due:).
   •	After typing the trigger, select a mention.
   •	**Observed Behavior:** No space is added, and when the mention is selected, the original word is deleted.

**Expected Behavior:**

•	In both cases, the behavior should be consistent: either always add a space after the mention and retain the original word, or provide an option to configure the behavior.
•	The selection of a mention should not result in the deletion of the text that follows, unless intended by the user.

**Impact:**
This inconsistency creates confusion for users who expect similar behaviors from different mention triggers. It also results in unintended text deletion, leading to potential data loss and the need for extra corrections.

**Environment:**

•	Version: [0.1.36]
•	Browser: [Chrome Version 128.0.6613.138 (Official Build) (arm64)]

**Comment by NatalyGraham** [comment]
After updating to version 0.1.42 and using the parameters autoSpace={false} and preTriggerChars=".*", the behavior is as follows:

1. Paste some text into the editor (e.g., “https://github.com/sodenn/lexical-beautiful-mentions/issues/661”).
2. Attempt to change “beautiful” to a mention (e.g., @Anton).
3. When selecting the appropriate mention, all text after the mention is deleted, resulting in: https://github.com/sodenn/lexical-@Anton.
4. However, if you add a space after the initial text (“https://github.com/sodenn/lexical-beautiful-mentions/issues/661 “) and repeat steps 2-3, everything works as expected: "https://github.com/sodenn/lexical-@Anton-mentions/issues/661 "

**Comment by sodenn** [comment]
@NatalyGraham: I’ve implemented a fix for this issue, which ensures that a space is inserted after a mention with a multi-character trigger. Could you please test it and let me know if it resolves the problem? Preview: https://lexical-beautiful-mentions-docs-git-fix-778371-sodenns-projects.vercel.app/?vercelToolbarCode=weI11ztag2ocpug&ospace=true
