### ISSUE TITLE
Getting console warning when type mention (@, #) key 

### ISSUE THREAD

**Issue by akashmdiu** [sodenn/lexical-beautiful-mentions#697]
Description: When using the <BeautifulMentionsPlugin> component with the items prop, React throws a warning:

Warning: React does not recognize the `items` prop on a DOM element.
This happens because items is being passed to a native DOM element, which React doesn't recognize as a valid attribute.

Steps to Reproduce:

Use the <BeautifulMentionsPlugin> component and pass an items prop, like so:

`<BeautifulMentionsPlugin items={mentionItems} />
`
Check the console to see the warning message:
`Warning: React does not recognize the `items` prop on a DOM element.`

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/ac720ecf-4ea1-4998-9b28-7022addec271">

Expected Behavior: React should not throw a warning, and the items prop should either be handled properly within the component or removed before being passed to any DOM elements.

Actual Behavior: The items prop is passed down to a DOM element, which causes React to throw a warning.

**Comment by sodenn** [comment]
Hi @akashmdiu, the `items`, `selected`, and `itemValue` props are provided to help building custom menu items. If you don't need this customization, you can simply exclude these props when spreading the remaining props to the DOM element.

```tsx
export const MenuItem = forwardRef<
  HTMLLIElement,
  BeautifulMentionsMenuItemProps
>(({ selected, item, itemValue, ...props }, ref) => (
  <li
    ref={ref}
    className={cn(
      "relative select-none ...",
      selected && "bg-accent ..."
    )}
    {...props}
  />
));
```

**Comment by allenfuller** [comment]
Hi there, new user to this plugin and experiencing the same issue. When I type "@" or "#" I get the DOM error.

When I implement the [custom menu](https://github.com/sodenn/lexical-beautiful-mentions/blob/main/www/components/Menu.tsx) from CodeSandbox example, it works.

🤷‍♂
