### ISSUE TITLE
Initial @names or #tags are clipped to 5 results

### ISSUE THREAD

**Issue by be-here-meow** [sodenn/lexical-beautiful-mentions#782]
**Title:** Results are clipped to 5 when adding @names or #tags with initial values in Beautiful Mentions Lexical Package  

**Describe the bug**  
When using the Beautiful Mentions Lexical package, adding @names or #tags initially clips the results to only 5 items. Any additional items beyond the first 5 are ignored. However, after the package is initiated, additional items can be added one by one. 

**To Reproduce**  
1. Initialize the Beautiful Mentions Lexical package with a list of @names or #tags (e.g., the provided example list).  
2. Attempt to use the mentions or tags functionality.  
3. Observe that only the first 5 results are displayed or recognized, clipping at "Elena."  

**Expected behavior**  
All initial @names or #tags should be recognized and displayed without being clipped to 5 results. The behavior should be consistent whether items are added during initialization or afterward.  

**Additional context**  
This issue can be observed in the published demo. The demo is imitated with the following list:  
```json
[
  "Anton",
  "Boris",
  "Catherine",
  "Dmitri",
  "Elena",
  "Felix",
  { value: "Gina", id: "1", avatar: null },
  { value: "Gina", id: "2", avatar: "https://example.com/avatars/1.jpg" },
]
```  
The demo should show all items, but it clips at "Elena." This suggests a potential default limit or configuration issue during initialization.  

You can see John in the list, only because it's added programmatically afterwards. Felix and Gina are never added.

https://lexical-beautiful-mentions-docs.vercel.app/

**Comment by be-here-meow** [comment]
It appears there is a `menuItemLimit` option that is currently undocumented. This option controls the number of results displayed in the mentions dropdown and defaults to 5 if not explicitly set. Adding this to the documentation would help prevent confusion and make it easier for developers to customize the behavior as needed.

```js
menuItemLimit: false, // Remove the limit
menuItemLimit: 20, // Show up to 20 results
menuItemLimit: { "@": 10, "#": 20 }, // Different limits for different triggers
```

**Comment by RohanRajGautam** [comment]
> **Title:** Results are clipped to 5 when adding @NAMEs or #tags with initial values in Beautiful Mentions Lexical Package
> 
> **Describe the bug** When using the Beautiful Mentions Lexical package, adding @NAMEs or #tags initially clips the results to only 5 items. Any additional items beyond the first 5 are ignored. However, after the package is initiated, additional items can be added one by one.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Initialize the Beautiful Mentions Lexical package with a list of @NAMEs or #tags (e.g., the provided example list).
> 2. Attempt to use the mentions or tags functionality.
> 3. Observe that only the first 5 results are displayed or recognized, clipping at "Elena."
> 
> **Expected behavior** All initial @NAMEs or #tags should be recognized and displayed without being clipped to 5 results. The behavior should be consistent whether items are added during initialization or afterward.
> 
> **Additional context** This issue can be observed in the published demo. The demo is imitated with the following list:
> 
> ```json
> [
>   "Anton",
>   "Boris",
>   "Catherine",
>   "Dmitri",
>   "Elena",
>   "Felix",
>   { value: "Gina", id: "1", avatar: null },
>   { value: "Gina", id: "2", avatar: "https://example.com/avatars/1.jpg" },
> ]
> ```
> 
> The demo should show all items, but it clips at "Elena." This suggests a potential default limit or configuration issue during initialization.
> 
> You can see John in the list, only because it's added programmatically afterwards. Felix and Gina are never added.
> 
> https://lexical-beautiful-mentions-docs.vercel.app/

there is a prop called `menuItemLimit` just set to your preference.

eg:
```
<BeautifulMentionsPlugin
  items={mentionsConfig}
  menuComponent={Menu}
  menuItemComponent={MenuItem}
  triggers={["@"]}
  menuItemLimit={1000}
/>
```
